import type { Metadata } from "next";
import { Inter } from "next/font/google";
import New from "./page";
import Sidebar from "./sidebar";
import NavBar from "../navBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function NewLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main>
            <header className="flex-col md:flex-row md:flex">
                <div className="h-full">
                    <Sidebar />
                </div>
                <div className="w-full h-[100%]">
                    {children}
                </div>
            </header>
        </main>
    );
}
