import type { Metadata } from "next";
import { Inter } from "next/font/google";
import New from "./page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function NewLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main>
            <header className="flex">
                    {children}
            </header>
        </main>
    );
}
